apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: community-platform
  labels:
    app: neo4j
    component: core
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "2004"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: ClusterIP
  selector:
    app: neo4j
    component: core
  ports:
    - name: http
      port: 7474
      targetPort: 7474
      protocol: TCP
    - name: bolt
      port: 7687
      targetPort: 7687
      protocol: TCP
    - name: https
      port: 7473
      targetPort: 7473
      protocol: TCP
    - name: backup
      port: 6362
      targetPort: 6362
      protocol: TCP
    - name: metrics
      port: 2004
      targetPort: 2004
      protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800