apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
  namespace: community-platform
  labels:
    app: community-platform
    environment: ${ENVIRONMENT}
    managed-by: terraform
  annotations:
    rotation-schedule: 30d
    last-rotated: ${LAST_ROTATION_TIMESTAMP}
    encryption: aes256-gcm
    vault.hashicorp.com/agent-inject: 'true'
type: Opaque
stringData:
  api_gateway_secrets.yaml:
    clerk:
      apiKey: ${CLERK_API_KEY}
      secretKey: ${CLERK_SECRET_KEY}
      webhookSecret: ${CLERK_WEBHOOK_SECRET}
      jwtPublicKey: ${CLERK_JWT_PUBLIC_KEY}
    redis:
      url: ${REDIS_URL}
      password: ${REDIS_PASSWORD}
      tlsCert: ${REDIS_TLS_CERT}
      tlsKey: ${REDIS_TLS_KEY}
    jwt:
      secretKey: ${JWT_SECRET_KEY}
      privateKey: ${JWT_PRIVATE_KEY}
      publicKey: ${JWT_PUBLIC_KEY}
      algorithm: RS256
      expiryTime: 1h
    monitoring:
      newRelicKey: ${NEW_RELIC_LICENSE_KEY}
      prometheusAuth: ${PROMETHEUS_AUTH_TOKEN}

  analytics_service_secrets.yaml:
    neo4j:
      uri: ${ANALYTICS_NEO4J_URI}
      username: ${ANALYTICS_NEO4J_USER}
      password: ${ANALYTICS_NEO4J_PASSWORD}
      tlsCert: ${ANALYTICS_NEO4J_TLS_CERT}
    metrics:
      apiKey: ${METRICS_API_KEY}
      endpoint: ${METRICS_ENDPOINT}
      region: ${AWS_REGION}
    storage:
      s3AccessKey: ${ANALYTICS_S3_ACCESS_KEY}
      s3SecretKey: ${ANALYTICS_S3_SECRET_KEY}
      bucketName: ${ANALYTICS_S3_BUCKET}

  event_service_secrets.yaml:
    neo4j:
      uri: ${EVENT_NEO4J_URI}
      username: ${EVENT_NEO4J_USER}
      password: ${EVENT_NEO4J_PASSWORD}
      tlsCert: ${EVENT_NEO4J_TLS_CERT}
    luma:
      apiKey: ${LUMA_API_KEY}
      apiSecret: ${LUMA_API_SECRET}
      webhookSecret: ${LUMA_WEBHOOK_SECRET}
      environment: ${LUMA_ENVIRONMENT}
    eventbrite:
      apiKey: ${EVENTBRITE_API_KEY}
      apiSecret: ${EVENTBRITE_API_SECRET}
      oauthToken: ${EVENTBRITE_OAUTH_TOKEN}
      webhookKey: ${EVENTBRITE_WEBHOOK_KEY}
    partiful:
      apiKey: ${PARTIFUL_API_KEY}
      apiSecret: ${PARTIFUL_API_SECRET}
      clientId: ${PARTIFUL_CLIENT_ID}
      webhookSecret: ${PARTIFUL_WEBHOOK_SECRET}

  member_service_secrets.yaml:
    neo4j:
      uri: ${MEMBER_NEO4J_URI}
      username: ${MEMBER_NEO4J_USER}
      password: ${MEMBER_NEO4J_PASSWORD}
      tlsCert: ${MEMBER_NEO4J_TLS_CERT}
    linkedin:
      clientId: ${LINKEDIN_CLIENT_ID}
      clientSecret: ${LINKEDIN_CLIENT_SECRET}
      oauthRedirectUri: ${LINKEDIN_OAUTH_REDIRECT_URI}
      webhookSecret: ${LINKEDIN_WEBHOOK_SECRET}
    gmail:
      clientId: ${GMAIL_CLIENT_ID}
      clientSecret: ${GMAIL_CLIENT_SECRET}
      refreshToken: ${GMAIL_REFRESH_TOKEN}
      oauthRedirectUri: ${GMAIL_OAUTH_REDIRECT_URI}
    storage:
      s3AccessKey: ${MEMBER_S3_ACCESS_KEY}
      s3SecretKey: ${MEMBER_S3_SECRET_KEY}
      bucketName: ${MEMBER_S3_BUCKET}