apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: community-platform
  labels:
    app: redis
    component: cache
    tier: data
    managed-by: kubernetes
  annotations:
    service.kubernetes.io/topology-aware-hints: "auto"
    prometheus.io/scrape: "true"
    prometheus.io/port: "6379"
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
      protocol: TCP
  selector:
    app: redis
    component: cache
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800