apiVersion: v1
kind: Service
metadata:
  name: event-service
  namespace: community-platform
  labels:
    app: event-service
    component: events
    part-of: community-platform
    managed-by: kubernetes
    version: v1
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "4001"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - port: 4001
      targetPort: 4001
      protocol: TCP
      name: grpc
  selector:
    app: event-service
    component: events
  sessionAffinity: None
  publishNotReadyAddresses: false