apiVersion: v1
kind: Service
metadata:
  name: member-service
  namespace: community-platform
  labels:
    app: member-service
    component: backend
    tier: service
    managed-by: kubernetes
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
    prometheus.io/scheme: "http"
    service.kubernetes.io/description: "Member Service gRPC and metrics endpoints"
    service.kubernetes.io/version: "1.0.0"
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 4000
      targetPort: grpc
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
  selector:
    app: member-service
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800